/**
 * Sync data/private/logins-keys.csv → src/lib/vaultBootstrap.local.ts (gitignored).
 * Run after updating the CSV so empty browsers re-seed on next load (dev/agent builds).
 *
 * Usage: npx tsx scripts/sync-vault-bootstrap.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const csvPath = resolve(root, 'data/private/logins-keys.csv')
const outPath = resolve(root, 'src/lib/vaultBootstrap.local.ts')

function splitCsvLine(line: string): string[] {
  const result: string[] = []
  let cur = ''
  let inQ = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!
    if (inQ) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cur += '"'
          i++
        } else {
          inQ = false
        }
      } else {
        cur += c
      }
    } else if (c === '"') {
      inQ = true
    } else if (c === ',') {
      result.push(cur)
      cur = ''
    } else {
      cur += c
    }
  }
  result.push(cur)
  return result
}

function parseVaultCsv(text: string): Array<Record<string, string>> {
  const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/)
  if (lines.length < 2) return []
  const headers = splitCsvLine(lines[0]!).map((h) => h.trim())
  const out: Array<Record<string, string>> = []
  let i = 1
  while (i < lines.length) {
    let line = lines[i]!
    if (!line.trim()) {
      i++
      continue
    }
    while ((line.match(/"/g) ?? []).length % 2 === 1 && i + 1 < lines.length) {
      i++
      line += '\n' + lines[i]
    }
    const cols = splitCsvLine(line)
    const row: Record<string, string> = {}
    headers.forEach((h, idx) => {
      row[h] = cols[idx] ?? ''
    })
    out.push(row)
    i++
  }
  return out
}

function tsString(s: string): string {
  return JSON.stringify(s)
}

const text = readFileSync(csvPath, 'utf8')
const rows = parseVaultCsv(text).filter(
  (r) => (r.label || r.service_name || r.api_key || r.username || '').trim(),
)

const entries = rows.map((r) => {
  const label = (r.label || r.service_name || '').trim()
  const typeRaw = (r.credential_type || '').trim().toLowerCase()
  const credential_type =
    typeRaw === 'api_key' || typeRaw === 'both' || typeRaw === 'login'
      ? typeRaw
      : r.api_key && !r.username && !r.password
        ? 'api_key'
        : r.api_key
          ? 'both'
          : 'login'
  const parts = [
    `    label: ${tsString(label)},`,
    `    credential_type: ${tsString(credential_type)} as const,`,
  ]
  if (r.username) parts.push(`    username: ${tsString(r.username)},`)
  if (r.password) parts.push(`    password: ${tsString(r.password)},`)
  if (r.api_key) parts.push(`    api_key: ${tsString(r.api_key)},`)
  if (r.url) parts.push(`    url: ${tsString(r.url)},`)
  if (r.notes) parts.push(`    notes: ${tsString(r.notes)},`)
  return `  {\n${parts.join('\n')}\n  }`
})

const file = `/**
 * Local-only vault seed — gitignored. Do not commit.
 * Generated by scripts/sync-vault-bootstrap.ts from data/private/logins-keys.csv
 * (${entries.length} entries · ${new Date().toISOString().slice(0, 10)})
 */
export const VAULT_BOOTSTRAP_ENTRIES = [
${entries.join(',\n')},
]
`

writeFileSync(outPath, file, { mode: 0o600 })
console.log(`Wrote ${entries.length} entries → ${outPath}`)
